#!/usr/bin/env python3
"""
Scraper for ville-ideale.fr — Île-de-France cities.
Uses Playwright (real Chromium browser) to avoid bot detection.

REQUIRES:
    communes_idf.csv        — generated by fetch_communes.py
    ville_ideale_idf.csv    — output (created if absent, appended to on resume)
    checkpoint.txt          — tracks done slugs (created automatically)

SETUP:
    pip install playwright beautifulsoup4
    playwright install chromium

RUN:
    python ville_ideale_scraper.py

LOGIC:
    ✅ Page loads with scores (numbers)  → save + checkpoint
    ✅ Page loads with dashes (no ratings yet) → save + checkpoint (valid result)
    ⚠️ Page body is empty/blank (white screen) → do NOT checkpoint, retry next run
"""

import csv
import logging
import random
import re
import subprocess
import time
from pathlib import Path

from bs4 import BeautifulSoup
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeout

# ── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ── Config ─────────────────────────────────────────────────────────────────────
COMMUNES_FILE   = "communes_idf.csv"
OUTPUT_FILE     = "ville_ideale_idf.csv"
CHECKPOINT_FILE = "checkpoint.txt"

DELAY_MIN = 60.0
DELAY_MAX = 75.0

LONG_PAUSE_EVERY = 10
LONG_PAUSE_MIN   = 120.0
LONG_PAUSE_MAX   = 180.0

BLOCK_BACKOFF_MIN = 45.0
BLOCK_BACKOFF_MAX = 90.0

# Stop after this many consecutive truly blank pages
MAX_CONSECUTIVE_BLOCKS = 5

BASE_URL = "https://www.ville-ideale.fr"

CRITERIA = [
    "Environnement",
    "Transports",
    "Sécurité",
    "Santé",
    "Sports et loisirs",
    "Culture",
    "Enseignement",
    "Commerces",
    "Qualité de vie",
]

FIELDNAMES = ["Nom", "Code INSEE", "Code postal", "Département", "Slug"] + CRITERIA


# ── Mac notification ───────────────────────────────────────────────────────────

def notify(title: str, message: str) -> None:
    try:
        script = f'display notification "{message}" with title "{title}" sound name "Glass"'
        subprocess.run(["osascript", "-e", script], check=True)
    except Exception:
        pass


# ── Load city list ─────────────────────────────────────────────────────────────

def load_communes(path: str) -> list[dict]:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(
            f"{path} not found. Run fetch_communes.py first to generate it."
        )
    with open(p, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


# ── Checkpoint ─────────────────────────────────────────────────────────────────

def load_checkpoint() -> set[str]:
    p = Path(CHECKPOINT_FILE)
    return set(p.read_text().splitlines()) if p.exists() else set()


def save_checkpoint(slug: str) -> None:
    """Called on success (scores or dashes). Never called for blank pages."""
    with open(CHECKPOINT_FILE, "a") as f:
        f.write(slug + "\n")


# ── Page parser ────────────────────────────────────────────────────────────────

def is_blank_page(html: str) -> bool:
    """
    Returns True if the page is a white screen / empty body —
    meaning the site blocked us or returned nothing useful.
    We check for the presence of the scores table AND the h1 city header.
    Dashes in the table are fine — that just means no ratings yet.
    """
    return "tablonotes" not in html and "<h1>" not in html


def parse_page(html: str, commune: dict) -> dict:
    soup = BeautifulSoup(html, "html.parser")

    # City name + zip from <h1>CLICHY (92110)</h1>
    h1 = soup.find("h1")
    h1_text = h1.get_text(strip=True) if h1 else ""
    zip_match = re.search(r"\((\d{5})\)", h1_text)
    zip_code  = zip_match.group(1) if zip_match else commune.get("Code postal", "")
    city_name = re.sub(r"\s*\(\d{5}\).*", "", h1_text).strip().title() or commune["Nom"]

    # Department from <strong>92 - Hauts-de-Seine</strong>
    dept_tag = soup.find("strong", string=re.compile(r"^\d{2}\s*-"))
    dept_str = dept_tag.get_text(strip=True) if dept_tag else commune.get("Département", "")

    # Scores from <table id="tablonotes">
    # Values are numbers like "3,62" or dashes "-" (no ratings yet)
    # Dashes are stored as empty string — the city is still checkpointed
    scores = {c: "" for c in CRITERIA}
    table = soup.find("table", id="tablonotes")
    if table:
        for row in table.find_all("tr"):
            th = row.find("th")
            td = row.find("td")
            if th and td:
                criterion = th.get_text(strip=True)
                if criterion in scores:
                    val = td.get_text(strip=True)
                    # Store actual numbers; treat dashes as empty (no rating)
                    scores[criterion] = val.replace(",", ".") if val != "-" else ""

    return {
        "Nom":         city_name,
        "Code INSEE":  commune.get("Code INSEE", ""),
        "Code postal": zip_code,
        "Département": dept_str,
        "Slug":        commune["Slug"],
        **scores,
    }


# ── Timing ─────────────────────────────────────────────────────────────────────

def polite_sleep(n_success: int) -> None:
    if n_success > 0 and n_success % LONG_PAUSE_EVERY == 0:
        t = random.uniform(LONG_PAUSE_MIN, LONG_PAUSE_MAX)
        log.info(f"  ↩  Long break ({t:.0f}s) after {n_success} scrapes …")
        time.sleep(t)
    else:
        time.sleep(random.uniform(DELAY_MIN, DELAY_MAX))


# ── Main ────────────────────────────────────────────────────────────────────────

def main():
    communes = load_communes(COMMUNES_FILE)
    done     = load_checkpoint()
    pending  = [c for c in communes if c["Slug"] not in done]

    log.info(f"Total: {len(communes)} | Done: {len(done)} | Pending: {len(pending)}")

    if not pending:
        log.info("All communes already scraped. Nothing to do.")
        notify("Scraper", "All cities already scraped — nothing to do.")
        return

    file_exists = Path(OUTPUT_FILE).exists()
    n_success          = 0
    n_blank            = 0
    consecutive_blanks = 0
    stop_reason        = "completed"

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)  # set True to hide window
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
            locale="fr-FR",
            timezone_id="Europe/Paris",
        )
        page = context.new_page()

        log.info("Visiting homepage to establish session …")
        try:
            page.goto(BASE_URL, wait_until="domcontentloaded", timeout=30000)
            time.sleep(random.uniform(2, 4))
        except PlaywrightTimeout:
            log.warning("Homepage timed out — continuing anyway")

        with open(OUTPUT_FILE, "a", newline="", encoding="utf-8-sig") as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=FIELDNAMES)
            if not file_exists:
                writer.writeheader()

            for commune in pending:
                slug = commune["Slug"]
                url  = f"{BASE_URL}/{slug}"

                remaining = len(pending) - n_success - n_blank
                log.info(f"[✅{n_success} ⚠️{n_blank} ⏳{remaining}] {slug}")

                polite_sleep(n_success)

                # ── Fetch ──────────────────────────────────────────────────
                try:
                    page.goto(url, wait_until="domcontentloaded", timeout=30000)
                    # Wait for h1 — present on both rated and unrated cities
                    page.wait_for_selector("h1", timeout=10000)
                    html = page.content()
                except PlaywrightTimeout:
                    html = page.content()

                # ── Blank page — site blocked us ───────────────────────────
                if is_blank_page(html):
                    n_blank += 1
                    consecutive_blanks += 1
                    log.warning(
                        f"  ⚠ Blank page ({consecutive_blanks}/{MAX_CONSECUTIVE_BLOCKS}) "
                        f"— NOT checkpointing, will retry next run"
                    )

                    if consecutive_blanks >= MAX_CONSECUTIVE_BLOCKS:
                        stop_reason = "blocked"
                        log.error(
                            f"\n  ✋ {MAX_CONSECUTIVE_BLOCKS} consecutive blank pages — stopping."
                            f"\n     Change VPN server and re-run to continue."
                            f"\n     {n_success} cities saved so far."
                        )
                        break

                    backoff = random.uniform(BLOCK_BACKOFF_MIN, BLOCK_BACKOFF_MAX)
                    log.info(f"  Backing off {backoff:.0f}s …")
                    time.sleep(backoff)
                    continue  # NOT checkpointed — will retry

                # ── Success: scores or dashes — both are valid ──────────────
                consecutive_blanks = 0
                n_success += 1

                row = parse_page(html, commune)
                writer.writerow(row)
                csvfile.flush()
                save_checkpoint(slug)  # checkpointed regardless of scores or dashes

                has_scores = any(row.get(c) for c in CRITERIA)
                score_info = (
                    " | ".join(f"{c[:4]}:{row[c]}" for c in CRITERIA if row[c])
                    if has_scores else "no ratings yet"
                )
                log.info(f"  ✅ {row['Nom']:30s} | {row['Code postal']} | {score_info}")

        browser.close()

    # ── Summary + Mac notification ─────────────────────────────────────────
    remaining = len(pending) - n_success - n_blank
    summary = f"Saved: {n_success} | Blank/skipped: {n_blank} | Still pending: {remaining}"
    log.info(f"\nSession done. {summary}")

    if stop_reason == "blocked":
        notify(
            "🚫 Scraper blocked",
            f"Stopped after {MAX_CONSECUTIVE_BLOCKS} blank pages. "
            f"{n_success} cities saved. Change VPN and re-run."
        )
    else:
        notify(
            "✅ Scraper finished",
            f"All done! {n_success} cities saved to {OUTPUT_FILE}."
        )


if __name__ == "__main__":
    main()
